import { createDepsRef } from './modules/core/deps.js'
import { createCoreModule } from './modules/core/index.js'
import { featureModules } from './service.js'

/**
 * What this image contains, printed as JSON.
 *
 *   node dist/manifest.js
 *
 * The release feed is generated by asking each published image this question, so what an admin is
 * told a release changes comes from the artefact itself rather than from a list somebody remembered
 * to edit. It touches no database and no network — the module definitions are all it reads.
 */
const modules = [createCoreModule(createDepsRef()), ...featureModules]

console.log(
  JSON.stringify({
    service: 'core',
    kernVersion: process.env.KERN_VERSION ?? '0.0.0-dev',
    modules: Object.fromEntries(modules.map((m) => [m.definition.id, m.definition.version])),
  }),
)
